version: 2

build:
  os: ubuntu-22.04
  tools:
      python: "3.11"       
  jobs:
    post_install:
      - pip install poetry     

python:
  system_packages: false

sphinx:
  configuration: docs/conf.py
