# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: poetry
      path: .
  system_packages: false

sphinx:
  configuration: docs/conf.py

